<?php

use Nette\Config\Configurator;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';

$configurator = new Configurator();

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(array(
		'188.121.172.183', // samo
		'149.62.146.153', // Pto Brno Lucka
		'89.102.3.159', // Pto Brno Lucka2
	));
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../vendor/others')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon', FALSE);

$host = $_SERVER['HTTP_HOST'];
if (preg_match('/pilotincommand\.com$/i', $host)) {
    $configurator->addConfig(__DIR__ . '/config/config.master.neon', FALSE);
} else {
    $configurator->addConfig(__DIR__ . '/config/config.local.neon', FALSE);
}

\Kdyby\Replicator\Container::register();

// Extensions
require __DIR__ . '/extensions.php';

$container = $configurator->createContainer();

return $container;
